### ISSUE TITLE
wrong format for `x-amz-date`

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/docs#213]
[Amazon docs](https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html) and some [Yandex Cloud docs](https://cloud.yandex.ru/docs/storage/concepts/pre-signed-urls) describe `x-amz-date` as having ISO 8601 format: `YYYYMMDD'T'HHMMSS'Z'`.
But the following page says it has another format: `Thu, 18 Jan 2018 09:57:35 GMT`
https://cloud.yandex.ru/docs/storage/s3/api-ref/common-request-headers

I suppose the last format is wrong and the page s/b corrected

**Comment by iglunchadze** [comment]
Thanks for pointing this out @AlexElin! The Object Storage team confirmed that this is indeed a bug, and values of the `x-amz-date` header must be in `YYYYMMDD'T'HHMMSS'Z'` format. We'll fix the bug and publish an updated version of the docs shortly.

**Comment by iglunchadze** [comment]
Fixed in [Russian](https://cloud.yandex.ru/docs/storage/s3/api-ref/common-request-headers#:~:text=HTTP%2F1.0%20%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2.-,x-amz-date,-%D0%94%D0%B0%D1%82%D0%B0%20%D0%B8%20%D0%B2%D1%80%D0%B5%D0%BC%D1%8F) and [English](https://cloud.yandex.com/en/docs/storage/s3/api-ref/common-request-headers#:~:text=HTTP%2F1.0%20requests.-,x-amz-date,-The%20date%20and) docs.
