### ISSUE TITLE
Include checksums for yc binaries on YC CLI releases page

### ISSUE THREAD

**Issue by antonalekseev** [yandex-cloud/docs#53]
It would be much appreciated if you could include checksums for `yc` binaries for every architecture it's built on the [releases page](https://cloud.yandex.ru/docs/cli/release-notes) (and it's russian counterpart). This would facilitate building binary packages of `yc` in order to deploy it conveniently in environments where `curl install.sh| bash` is absolutely a non-starter. Not sure though it's a right channel for such requests to make, so feel free to close and ignore if it isn't.

**Comment by skipor** [comment]
Hello! Thank you for your feedback.
We will include checksums for `yc` binaries on release page from some point in future. 

If it makes situation better, now you can pre-download `install.sh`, read it and understand that it is safe to run it on your environment, then run your downloaded copy. It just downloads "latest" `yc`  and set $PATH actually. Yes, there is no checksum validation, but by downloading binary by HTTPS, you may be confident , that what your get is exactly same binary, what we had released.

To track status of feature request, it's better to add request at https://cloud.yandex.ru/features or send request to support. 

This issue is not related to current repository, so we will close it.
